In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [44]:
df = pd.read_excel('Flight_price_prediction.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

### Spliting Date_of_Journey Column into date , month and year column

In [45]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split("/").str[2]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(13)
memory usage: 1.1+ MB

### Converting Date,Month,Year column from object type to int type

In [47]:
df['Date'] = df['Date'].astype('int')
df['Month'] = df['Month'].astype('int')
df['Year'] = df['Year'].astype('int')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.1+ MB

In [49]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

### Droping the Date_of_Journey Columns

In [50]:
df.drop('Date_of_Journey' , axis=1 , inplace = True)

In [51]:
df.head(1)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019

### Spliting Arrival Time column to Arrival hours and Arrival Minutes

In [52]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x:x.split(" ")[0])

In [53]:
df['Arrival_Hrs'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Min'] = df['Arrival_Time'].str.split(':').str[1]

In [54]:
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hrs,Arrival_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_Hrs      10683 non-null  object
 14  Arrival_Min      10683 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.2+ MB

### Converting Arrival_Hrs and arrival_Min column from object type to int type

In [56]:
df['Arrival_Hrs'] = df['Arrival_Hrs'].astype('int')
df['Arrival_Min'] = df['Arrival_Min'].astype('int')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Arrival_Time     10683 non-null  object
 6   Duration         10683 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10683 non-null  object
 9   Price            10683 non-null  int64
 10  Date             10683 non-null  int64
 11  Month            10683 non-null  int64
 12  Year             10683 non-null  int64
 13  Arrival_Hrs      10683 non-null  int64
 14  Arrival_Min      10683 non-null  int64
dtypes: int64(6), object(9)
memory usage: 1.2+ MB

### Droping Arrival_Time Column

In [58]:
df.drop("Arrival_Time" , axis=1 , inplace=True)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10683 non-null  object
 5   Duration         10683 non-null  object
 6   Total_Stops      10682 non-null  object
 7   Additional_Info  10683 non-null  object
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hrs      10683 non-null  int64
 13  Arrival_Min      10683 non-null  int64
dtypes: int64(6), object(8)
memory usage: 1.1+ MB

### Spliting Departure time into hours and minutes

In [60]:
df['Dep_Hrs'] = df['Dep_Time'].str.split(':').str[0]
df['Dep_Min'] = df['Dep_Time'].str.split(':').str[1]

### Converting Dep_Hrs and Dep_Min column from object type to int type

In [61]:
df['Dep_Hrs'] = df['Dep_Hrs'].astype('int')
df['Dep_Min'] = df['Dep_Min'].astype('int')

### Droping Dep_Time Column

In [62]:
df.drop('Dep_Time' , axis=1 , inplace=True)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hrs      10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Dep_Hrs          10683 non-null  int64
 14  Dep_Min          10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10683 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10683 non-null  object
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  int64
 9   Month            10683 non-null  int64
 10  Year             10683 non-null  int64
 11  Arrival_Hrs      10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Dep_Hrs          10683 non-null  int64
 14  Dep_Min          10683 non-null  int64
dtypes: int64(8), object(7)
memory usage: 1.2+ MB

### Checking Categories on Total_stops

In [65]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [66]:
# Checking how many nan value present in Total_stops Column
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hrs,Arrival_Min,Dep_Hrs,Dep_Min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

#### Mapping and labeling the total_stops column

In [67]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop' : 0 , '1 stop' : 1 , "2 stops" : 2 , '3 stops': 3 , '4 stop' : 4})
df['Total_Stops'] = df['Total_Stops'].fillna(1)

In [68]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hrs,Arrival_Min,Dep_Hrs,Dep_Min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,No info,13302,1,3,2019,21,35,16,50

In [69]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hrs, Arrival_Min, Dep_Hrs, Dep_Min]
Index: []

### Droping Route Column

In [70]:
df.drop("Route" , axis=1 , inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Duration         10683 non-null  object
 4   Total_Stops      10683 non-null  float64
 5   Additional_Info  10683 non-null  object
 6   Price            10683 non-null  int64
 7   Date             10683 non-null  int64
 8   Month            10683 non-null  int64
 9   Year             10683 non-null  int64
 10  Arrival_Hrs      10683 non-null  int64
 11  Arrival_Min      10683 non-null  int64
 12  Dep_Hrs          10683 non-null  int64
 13  Dep_Min          10683 non-null  int64
dtypes: float64(1), int64(8), object(5)
memory usage: 1.1+ MB

In [72]:
df['Duration'].head()

0    2h 50m
1    7h 25m
2       19h
3    5h 25m
4    4h 45m
Name: Duration, dtype: object

In [73]:
df.loc[df['Duration'] == '5m', 'Duration'] = df['Duration'].mode()[0]

In [74]:
df['Duration_Hrs'] = df['Duration'].str.split(' ').str[0].str.split('h').str[0]
df['Duration_Min'] = df['Duration'].str.split(' ').str[1].str.split('m').str[0]

df['Duration_Min'] = df['Duration_Min'].fillna(0)

df['Duration_Hrs'].head()

0     2
1     7
2    19
3     5
4     4
Name: Duration_Hrs, dtype: object

In [75]:
df['Duration_Min'].head()

0    50
1    25
2     0
3    25
4    45
Name: Duration_Min, dtype: object

In [76]:
# def convert_duration(x):
#     hours = 0
#     minutes = 0

#     if 'h' in x:
#         hours = int(x.split('h')[0])

#     if 'm' in x:
#         if 'h' in x:
#             minutes = int(x.split('h')[1].replace('m',''))
#         else:
#             minutes = int(x.replace('m',''))

#     return hours * 60 + minutes

In [77]:
# df['Duration_min'] = df['Duration'].apply(convert_duration)

In [78]:
df[df['Duration'].str.contains('m') & ~df['Duration'].str.contains('h')]

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hrs, Arrival_Min, Dep_Hrs, Dep_Min, Duration_Hrs, Duration_Min]
Index: []

### Converting Duration_Hrs and Duration_Min to Integer

In [79]:
df['Duration_Hrs'] = df['Duration_Hrs'].astype("int")
df['Duration_Min'] = df['Duration_Min'].astype("int")

In [80]:
df.drop('Duration' , axis=1 , inplace=True)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Source           10683 non-null  object
 2   Destination      10683 non-null  object
 3   Total_Stops      10683 non-null  float64
 4   Additional_Info  10683 non-null  object
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hrs      10683 non-null  int64
 10  Arrival_Min      10683 non-null  int64
 11  Dep_Hrs          10683 non-null  int64
 12  Dep_Min          10683 non-null  int64
 13  Duration_Hrs     10683 non-null  int64
 14  Duration_Min     10683 non-null  int64
dtypes: float64(1), int64(10), object(4)
memory usage: 1.2+ MB

### Checking Unique Airlines Categories for applying one hot encoding

In [82]:
df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [83]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [84]:
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(),
    index=df.index
)
encoded_df.index = df.index

NameError: name 'encoded_array' is not defined

In [ ]:
df = df.drop(["Airline", "Source", "Destination" , "Additional_Info"], axis=1)

In [ ]:
df = pd.concat([df, encoded_df], axis=1)
df

,Total_Stops,Price,Date,Month,Year,Arrival_Hrs,Arrival_MIn,Dep_Hrs,Dep_Min,Duration_Hrs,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,3897,24,3,2019,1,10,22,20,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2.0,7662,1,5,2019,13,15,5,50,7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2.0,13882,9,6,2019,4,25,9,25,19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1.0,6218,12,5,2019,23,30,18,5,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.0,13302,1,3,2019,21,35,16,50,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,4107,9,4,2019,22,25,19,55,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,0.0,4145,27,4,2019,23,20,20,45,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,7229,27,4,2019,11,20,8,20,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,12648,1,3,2019,14,10,11,30,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,2.0,11753,9,5,2019,19,15,10,55,8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 44 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Total_Stops                                   10683 non-null  float64
 1   Price                                         10683 non-null  int64
 2   Date                                          10683 non-null  int64
 3   Month                                         10683 non-null  int64
 4   Year                                          10683 non-null  int64
 5   Arrival_Hrs                                   10683 non-null  int64
 6   Arrival_MIn                                   10683 non-null  int64
 7   Dep_Hrs                                       10683 non-null  int64
 8   Dep_Min                                       10683 non-null  int64
 9   Duration_Hrs                                  10683 non-null  int64
 10  Duration_Min                                  10683 non-null  int64
 11  Airline_Air Asia                              10683 non-null  float64
 12  Airline_Air India                             10683 non-null  float64
 13  Airline_GoAir                                 10683 non-null  float64
 14  Airline_IndiGo                                10683 non-null  float64
 15  Airline_Jet Airways                           10683 non-null  float64
 16  Airline_Jet Airways Business                  10683 non-null  float64
 17  Airline_Multiple carriers                     10683 non-null  float64
 18  Airline_Multiple carriers Premium economy     10683 non-null  float64
 19  Airline_SpiceJet                              10683 non-null  float64
 20  Airline_Trujet                                10683 non-null  float64
 21  Airline_Vistara                               10683 non-null  float64
 22  Airline_Vistara Premium economy               10683 non-null  float64
 23  Source_Banglore                               10683 non-null  float64
 24  Source_Chennai                                10683 non-null  float64
 25  Source_Delhi                                  10683 non-null  float64
 26  Source_Kolkata                                10683 non-null  float64
 27  Source_Mumbai                                 10683 non-null  float64
 28  Destination_Banglore                          10683 non-null  float64
 29  Destination_Cochin                            10683 non-null  float64
 30  Destination_Delhi                             10683 non-null  float64
 31  Destination_Hyderabad                         10683 non-null  float64
 32  Destination_Kolkata                           10683 non-null  float64
 33  Destination_New Delhi                         10683 non-null  float64
 34  Additional_Info_1 Long layover                10683 non-null  float64
 35  Additional_Info_1 Short layover               10683 non-null  float64
 36  Additional_Info_2 Long layover                10683 non-null  float64
 37  Additional_Info_Business class                10683 non-null  float64
 38  Additional_Info_Change airports               10683 non-null  float64
 39  Additional_Info_In-flight meal not included   10683 non-null  float64
 40  Additional_Info_No Info                       10683 non-null  float64
 41  Additional_Info_No check-in baggage included  10683 non-null  float64
 42  Additional_Info_No info                       10683 non-null  float64
 43  Additional_Info_Red-eye flight                10683 non-null  float64
dtypes: float64(34), int64(10)
memory usage: 3.6 MB

In [85]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hrs,Arrival_Min,Dep_Hrs,Dep_Min,Duration_Hrs,Duration_Min
0,IndiGo,Banglore,New Delhi,0.0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2.0,No info,7662,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2.0,No info,13882,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1.0,No info,6218,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1.0,No info,13302,1,3,2019,21,35,16,50,4,45

In [86]:
df.drop(['Date' , "Month" , "Year" , 'Additional_Info'] , axis=1 , inplace=True)

In [87]:
df.head()

,Airline,Source,Destination,Total_Stops,Price,Arrival_Hrs,Arrival_Min,Dep_Hrs,Dep_Min,Duration_Hrs,Duration_Min
0,IndiGo,Banglore,New Delhi,0.0,3897,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2.0,7662,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2.0,13882,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1.0,6218,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1.0,13302,21,35,16,50,4,45

In [88]:
df.corr(numeric_only=True)

,Total_Stops,Price,Arrival_Hrs,Arrival_Min,Dep_Hrs,Dep_Min,Duration_Hrs,Duration_Min
Total_Stops,1.000000,0.603731,0.038305,-0.106931,-0.061011,-0.003161,0.739774,-0.136437
Price,0.603731,1.000000,0.024264,-0.086155,0.006819,-0.024492,0.508724,-0.124431
Arrival_Hrs,0.038305,0.024264,1.000000,-0.154362,0.005215,0.043054,0.055190,-0.118250
Arrival_Min,-0.106931,-0.086155,-0.154362,1.000000,0.067909,-0.017594,-0.074400,0.152084
Dep_Hrs,-0.061011,0.006819,0.005215,0.067909,1.000000,-0.024806,0.002797,-0.023594
Dep_Min,-0.003161,-0.024492,0.043054,-0.017594,-0.024806,1.000000,-0.021916,0.092889
Duration_Hrs,0.739774,0.508724,0.055190,-0.074400,0.002797,-0.021916,1.000000,-0.126631
Duration_Min,-0.136437,-0.124431,-0.118250,0.152084,-0.023594,0.092889,-0.126631,1.000000

In [ ]:
from sklearn.model_selection import train_test_split

: